### ISSUE TITLE
Cant install on windows

### ISSUE THREAD

**Issue by StarpTech** [sirupsen/logrus#626]
```
go get github.com/sirupsen/logrus
```
```
# golang.org/x/crypto/ssh/terminal
..\..\..\golang.org\x\crypto\ssh\terminal\util_windows.go:42: undefined: windows.ENABLE_ECHO_INPUT
..\..\..\golang.org\x\crypto\ssh\terminal\util_windows.go:42: undefined: windows.ENABLE_PROCESSED_INPUT
..\..\..\golang.org\x\crypto\ssh\terminal\util_windows.go:42: undefined: windows.ENABLE_LINE_INPUT
..\..\..\golang.org\x\crypto\ssh\terminal\util_windows.go:42: undefined: windows.ENABLE_PROCESSED_OUTPUT
..\..\..\golang.org\x\crypto\ssh\terminal\util_windows.go:43: undefined: windows.SetConsoleMode
..\..\..\golang.org\x\crypto\ssh\terminal\util_windows.go:62: undefined: windows.SetConsoleMode
..\..\..\golang.org\x\crypto\ssh\terminal\util_windows.go:67: undefined: windows.ConsoleScreenBufferInfo
..\..\..\golang.org\x\crypto\ssh\terminal\util_windows.go:68: undefined: windows.GetConsoleScreenBufferInfo
..\..\..\golang.org\x\crypto\ssh\terminal\util_windows.go:91: undefined: windows.ENABLE_ECHO_INPUT
..\..\..\golang.org\x\crypto\ssh\terminal\util_windows.go:92: undefined: windows.ENABLE_PROCESSED_INPUT
..\..\..\golang.org\x\crypto\ssh\terminal\util_windows.go:92: too many errors
```

**Comment by dmathieu** [comment]
Do you have an old version of `x/crypto/ssh/terminal`? Could you try updating it?

**Comment by sudo-suhas** [comment]
I also faced this issue after updating to logrus `v1.0.3`. I am also able to reproduce the issue in a fresh project:

**glide.yaml:**
```yaml
package: playground
import:
- package: github.com/Sirupsen/logrus
  version: ^1.0.3
```

**glide.lock:**
```
hash: 63379b39e56eb058f5db6ba5e8a6fdba655701f90c3f11e6b7651d089cf31556
updated: 2017-08-21T15:35:36.2560978+05:30
imports:
- name: github.com/Sirupsen/logrus
  version: f006c2ac4710855cf0f916dd6b77acf6b048dc6e
- name: golang.org/x/crypto
  version: eb71ad9bd329b5ac0fd0148dd99bd62e8be8e035
  subpackages:
  - ssh/terminal
- name: golang.org/x/sys
  version: c4489faa6e5ab84c0ef40d6ee878f7a030281f0f
  subpackages:
  - unix
  - windows
testImports: []

```

**main.go:**
```go
package main

import log "github.com/Sirupsen/logrus"

func main() {
	log.WithFields(log.Fields{
		"animal": "walrus",
	}).Info("A walrus appears")
}

```

**Error:**
```console
$ go build .
# playground/vendor/golang.org/x/crypto/ssh/terminal
vendor\golang.org\x\crypto\ssh\terminal\util_windows.go:42: undefined: windows.ENABLE_ECHO_INPUT
vendor\golang.org\x\crypto\ssh\terminal\util_windows.go:42: undefined: windows.ENABLE_PROCESSED_INPUT
vendor\golang.org\x\crypto\ssh\terminal\util_windows.go:42: undefined: windows.ENABLE_LINE_INPUT
vendor\golang.org\x\crypto\ssh\terminal\util_windows.go:42: undefined: windows.ENABLE_PROCESSED_OUTPUT
vendor\golang.org\x\crypto\ssh\terminal\util_windows.go:43: undefined: windows.SetConsoleMode
vendor\golang.org\x\crypto\ssh\terminal\util_windows.go:62: undefined: windows.SetConsoleMode
vendor\golang.org\x\crypto\ssh\terminal\util_windows.go:67: undefined: windows.ConsoleScreenBufferInfo
vendor\golang.org\x\crypto\ssh\terminal\util_windows.go:68: undefined: windows.GetConsoleScreenBufferInfo
vendor\golang.org\x\crypto\ssh\terminal\util_windows.go:91: undefined: windows.ENABLE_ECHO_INPUT
vendor\golang.org\x\crypto\ssh\terminal\util_windows.go:92: undefined: windows.ENABLE_PROCESSED_INPUT
vendor\golang.org\x\crypto\ssh\terminal\util_windows.go:92: too many errors
```
